### PR TITLE
Add a new option to keep the prompt in two lines or one

### PR DESCRIPTION
**Pull request by gregf**
You'll probably want to merge this one first, it doesn't contain the chruby stuff.

### CODE REVIEW

**Comment by caiogondim** [comment]
Amazing!
Thanks for the PR.

**Comment by Strubbl** [comment]
that's a nice one! thanks a lot. i'll use this option :+1:

**Comment by sleepygarden** [comment]
This only works if this config is set before the theme is source, i have a small modification which supports changing inside of a session

    prompt_line_sep() {
        if [[ $BULLETTRAIN_PROMPT_SEP_LINE == true ]]; then
            # newline wont print without a non newline character, so add a zero width space
            echo -e '\n\u200B'
        fi
    }

    PROMPT='$(prompt_line_sep)%{%f%b%k%}$(build_prompt)$(prompt_line_sep)%{${fg_bold[default]}%}$(prompt_char) %{$reset_color%}'

**Comment by gregf** [comment]
@sleepygarden LGTM, but could you open a pull request, because this was already merged.

**Pull request merged**
