### PR TITLE
Shows context with dir and removes prompt_context

### PR DESCRIPTION
**Pull request by secrettriangle**

### CODE REVIEW

**Comment by caiogondim** [comment]
I guess it makes sense to have user/machine on a different segment, and you can achievement that same result using the same colors on the context and dir segments.

You ok with that?

screen shot 2015-01-05 at 22 53 12

**Comment by secrettriangle** [comment]
The reason I used `name@host:path` is because you could then copy/paste the path directly to `scp`. We could colorize parts of the path to make it more readable without detracting from scp-friendly paths.

**Comment by caiogondim** [comment]
Just tested your new pull request. 
Thanks again for the work.

Your idea makes a lot of sense, but i really like to have a user@machine in a different segment as well.
Maybe we should try to do both cases? 
Or just add your case to the segment dir and let the context segment untouched.

What you think?

**Comment by secrettriangle** [comment]
@caiogondim I've updated the PR. Now `prompt_context` stays in place. I've added an option `BULLETTRAIN_DIR_CONTEXT_SHOW` that adds the context to the path.

**Comment by caiogondim** [comment]
Awesome work again! Merged.

**Pull request merged**
