### PR TITLE
Add Go version to prompt, only displayed when in a go source tree

### PR DESCRIPTION
**Pull request by gregf**

### CODE REVIEW

**Comment by gregf** [comment]
Again the failure here appears to be with a previous commit in the readme. I'm not actually sure what has to be done to fix it off hand.

**Comment by caiogondim** [comment]
I will take a look on the broken master branch.

**Comment by caiogondim** [comment]
Made some fixes and merged.
Let me know what you think about it.

**Comment by gregf** [comment]
LGTM!

**Pull request closed without merging**
