### PR TITLE
prompt_char can now be any length

### PR DESCRIPTION
**Pull request by jzck**

### CODE REVIEW

**Comment by dawikur** [comment]
@jzck can you only merge it into single line?

**Comment by caiogondim** [comment]
@jzck Care to resolve the conflict?

**Comment by jzck** [comment]
@caiogondim I'm not sure what conflict I've just resolved, PR is still the same.
@dawikur I'm only adding a single line, not sure what you mean?

**Comment by dawikur** [comment]
@jzck I mean merging definition with assignment

from
```bash
local bt_prompt_chars
bt_prompt_chars="${BULLETTRAIN_PROMPT_CHAR}"
```

to

```bash
local bt_prompt_chars="${BULLETTRAIN_PROMPT_CHAR}"
```

**Pull request merged**
