### PR TITLE
Stop printing a blank line before every prompt

### PR DESCRIPTION
**Pull request by gregf**

### CODE REVIEW

**Comment by gregf** [comment]
The CI failure looks related to a previous README update?

**Comment by caiogondim** [comment]
I like this feature by default.
Maybe we should create one more flag to enable/disable it?

**Comment by gregf** [comment]
Sounds fair, I'll rework this later today

**Comment by caiogondim** [comment]
If you update your branch with master the tests should pass.

**Comment by gregf** [comment]
All set.

**Pull request merged**
