### PR TITLE
Testing npm without leting which and type output escape

### PR DESCRIPTION
**Pull request by gvillalta99**
This fix issue #38

### CODE REVIEW

**Comment by caiogondim** [comment]
Thanks so much for the contribution.

**Comment by caiogondim** [comment]
I was getting some syntax error and then changed the code a bit.
Would you mind testing the latest version and letting me know if it works on your machine?

**Comment by secrettriangle** [comment]
Actually I think we should be using `command` to check the existence of a command. See [here](https://github.com/slap-editor/slap/blob/master/install.sh#L5-L7) for usage.

**Comment by gvillalta99** [comment]
@caiogondim it's working fine here.
@secrettriangle `command` don't handle sourced functions like [`nvm`](https://github.com/creationix/nvm/blob/master/nvm.sh#L1094).

**Pull request merged**
