### PR TITLE
Display exec time as something like 2d3h31m5s instead of 185465s

### PR DESCRIPTION
**Pull request by yongqli**
Closes https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/issues/138

### CODE REVIEW

**Comment by dawikur** [comment]
Looks fine, but this allows also outputs like
`2d31m5s`
Wouldn't it be better to do
`2d0h31m5s`
?

**Comment by vadviktor** [comment]
In my case less characters in the already "bloated" prompt line is a blessing. I like the short version better, though I have a feeling this shouts out for a new config parameter ;) e.g. _SHORT / _LONG

**Comment by dawikur** [comment]
Yeah, that would be probably best solution. Can you provide proper PR?

**Comment by yongqli** [comment]
Maybe only show as days, hours, minutes, seconds if `BULLETTRAIN_EXEC_TIME_USE_DHMS=true`?

**Comment by dawikur** [comment]
Ok, lets merge this and if anything we can improve it in future.

**Pull request merged**
