### PR TITLE
Add user and hostname promtp segments

### PR DESCRIPTION
**Pull request by ovidiub13**

### CODE REVIEW

**Comment by gregf** [comment]
:+1:

**Comment by caiogondim** [comment]
Isn't it the same as BULLETTRAIN_CONTEXT_SHOW?

**Comment by ovidiub13** [comment]
On a fresh install of Debian and CentOS latest, I don't have the context command.

**Comment by ovidiub13** [comment]
Sorry: On centos I have the command and it returns this:
```
$ context 
ovidiu@%m%
```

**Comment by caiogondim** [comment]
@ovidiub13 You can use the **Custom** segment that was added.

**Comment by ovidiub13** [comment]
But that would imply having the possibility to have multiple Custom segments, is that allowed?

**Comment by LACabeza** [comment]
@ovidiub13 i made a  pull request (https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/pull/116) just now. If it is merged, you'd be able to assign 

    BULLETTRAIN_CONTEXT_HOSTNAME=$(hostname -a)

and it will work.

**Comment by ovidiub13** [comment]
@caiogondim does this pull request have any chance? if not. I'll close it.

**Comment by caiogondim** [comment]
For this one I'm willing to keep the code simpler, since we can do this with `BULLETTRAIN_CUSTOM_MSG`

If that not satisfy your user case, we can expand `BULLETTRAIN_CUSTOM_MSG` to be an array.

**Pull request closed without merging**
