### PR TITLE
Add reference to Input Mono, another powerline compatible font

### PR DESCRIPTION
**Pull request by unixorn**

### CODE REVIEW

**Comment by caiogondim** [comment]
Would you mind sending me a screenshot of the Input font with the theme, so i can approve the PR?

**Comment by unixorn** [comment]
Here you go:
inputmonoscreenshot

**Comment by caiogondim** [comment]
Thanks for the PR.

**Comment by caiogondim** [comment]
And BTW, you can align the triangles with the other segments by changing the vertical length of the characters.

Here is a screenshot of my setup.
screen shot 2015-03-28 at 12 26 15

**Pull request merged**
