### PR TITLE
Support for advanced usage in custom message

### PR DESCRIPTION
**Pull request by JayXon**
For example
```
export BULLETTRAIN_CUSTOM_MSG=\$SOME_ENV_I_WANT_TO_SHOW
export BULLETTRAIN_CUSTOM_MSG=\`some command I want to run\`
```

### CODE REVIEW

**Comment by dawikur** [comment]
Looks fine for me 👍

**Comment by caiogondim** [comment]
We need documentation on README as well.

**Comment by JayXon** [comment]
Is this enough? Or you want something in the Tips section?

**Comment by tunnckoCore** [comment]
:+1:

**Comment by JayXon** [comment]
Is there anything else I need to do to get this merged?

**Comment by dawikur** [comment]
I think this is fine. Merge 👍

**Pull request merged**
