### PR TITLE
Added plenv (PERL) segment

### PR DESCRIPTION
**Pull request by dmdavis**
* Added BULLETTRAIN_PERL_ shell variable checks to bullet-train.zsh-theme
* Added prompt_perl function

### CODE REVIEW

**Comment by dmdavis** [comment]
I recently found myself having to do some **PERL** work at a new job and wanted to add **[PLENV](https://github.com/tokuhirom/plenv)** support to your excellent zsh prompt. I'm not a **PERLBREW** user, so I didn't attempt to add support for that tool.

**Comment by caiogondim** [comment]
That is fantastic.
Would you mind adding documentation to README so I can merge the PR?

**Comment by dmdavis** [comment]
Added Perl configuration instructions to README.md.

**Comment by caiogondim** [comment]
Thanks for the PR.
Amazing work.

**Pull request merged**
