### PR TITLE
fix(kubernetes-context): added to default prompt order

### PR DESCRIPTION
**Pull request by Qwerios**
As requested here: https://github.com/caiogondim/bullet-train.zsh/pull/257#issuecomment-415733705

Added it just after the aws prompt which seemed like the proper place

### CODE REVIEW

**Review by topagae — APPROVED** [review]
I made this change myself, glad to see someone already fixed it. Merge it!

**Comment by topagae** [comment]
Sadly even when making this change I can't get the prompt to work. Saddening  =(

**Comment by Qwerios** [comment]
> Sadly even when making this change I can't get the prompt to work. Saddening =(

You still need to ensure the normal kubernetes configuration envs are set:
https://github.com/caiogondim/bullet-train.zsh#kubernetes-context

And you can verify that `kubectl config current-context` actually returns a value.

**Comment by topagae** [comment]
I very certainly did. I ran through every line and it was all kosher. Set
the env var. Tested it. Tested all the if statements. Tested the grep of
the config. For whatever reason it just doesn't render the prompt. Very
sad.

**Comment by drewgonzales360** [comment]
Hi I just ran into this. I can confirm it works :smile: Can we merge this?

**Comment by chris-lee-parsable** [comment]
I had to dig through and find this at a new job a year later and it's still not merged, sad!

**Comment by Qwerios** [comment]
Just going to close this. People can find this through search engines well enough

**Pull request closed without merging**
