### PR TITLE
Remove BULLETTRAIN_DIR_CONTEXT_SHOW since there is a CONTEXT segment

### PR DESCRIPTION
**Pull request by Lyncredible**
Also remove an extra space in go segment ("go 1.7" instead of "go  1.7")

### CODE REVIEW

**Comment by dbkaplun** [comment]
I use this particular segment as it can be copied directly to ssh/scp. Why are we removing it?

**Comment by dbkaplun** [comment]
As a matter of fact I think the recent attempts at refactoring/cleaning up the code base are a step backwards rather than forwards. I vote we stop trying to fix what isn't broken and focus on implementing new functionality rather than removing features.

**Comment by Lyncredible** [comment]
I updated to latest version and found duplicates between "context" segment and "dir_context" in "dir" segment.

Good call on copying to scp. I guess keeping dir_context inside dir is still useful.

**Comment by zv** [comment]
this is me doing  you a solid. post in #oh-my-zsh next time you sick fuck.

**Pull request closed without merging**
