### PR TITLE
Adding Rbenv support for RVM branch

### PR DESCRIPTION
**Pull request by vadviktor**
Adding Rbenv support for RVM branch, though now without rbenv-gemset support.

### CODE REVIEW

**Comment by vadviktor** [comment]
Do you think the **RVM** section to be renamed **Ruby**? That would make people to update their .zshrc files to do the overrides.
If I can rename that section, do I need to include any special mark in the Readme or a changelog?

**Comment by caiogondim** [comment]
Guess it makes more sense to rename it to Ruby.
And yes again, rename the README file with the new variable names for configuration.

**Comment by vadviktor** [comment]
Let me know if you need anything else on this.

**Comment by caiogondim** [comment]
That is amazing work.
Cheers @vadviktor

**Pull request merged**
