### PR TITLE
Adding Pyenv support to Python virtualenv as "fallback"

### PR DESCRIPTION
**Pull request by vadviktor**

### CODE REVIEW

**Comment by caiogondim** [comment]
Could you solve this conflict in order to merge the PR?

**Comment by vadviktor** [comment]
I have merged in the master and resolved current conflicts. Also I have used squash commit here so I don't know if the system will pick up and show that it is not broken anymore. Sorry, I have just started to do PRs recently, I have to get adjusted to it. :blush:

**Comment by vadviktor** [comment]
@caiogondim, any plan for this one? :)

**Comment by caiogondim** [comment]
Commit merged.
Let me know if something went wrong.

**Pull request merged**
