### PR TITLE
Add support for rbenv theming

### PR DESCRIPTION
**Pull request by CassioGodinho**
Adds a ruby version section if theres is a rbenv .ruby-version file on current directory.

### CODE REVIEW

**Comment by LimeBlast** [comment]
:+1:

**Comment by caiogondim** [comment]
I'm not a ruby guy, but i guess the `.ruby-version` file is the default method to declare which Ruby version you want.
If so, does it make sense to delete the *RVM* segment to use only this one?

**Comment by CassioGodinho** [comment]
Its been a while since I worked with ruby, but the last time I used *RVM* it required some [configuration ] (http://stackoverflow.com/questions/15708916/use-rvmrc-or-ruby-version-file-to-set-a-project-gemset-with-rvm) to work with `.ruby-version` files. I can check this, if I can use *RVM* without any extra configuration I guess its safe to remove the *RVM* segment.

**Comment by vadviktor** [comment]
I'd suggest converting the RVM segment to a generic ruby segment.
In one of the oh-my-zsh themes they just query for the presence of either RVM of Rbenv, which IMHO is a trustworthy solution. I use rbenv and I do not litter the folders with `.ruby-version` files. Still rbenv is told which is the system default, and that can be overridden temporarily on the current console. In these cases the `.ruby-version` will lie.

The theme uses this code to decide: (just to provide example)

```shell
local rvm=''
if which rvm-prompt &> /dev/null; then
  rvm='%{$fg[green]%}‹$(rvm-prompt i v g)›%{$reset_color%}'
else
  if which rbenv &> /dev/null; then
    rvm='%{$fg[green]%}‹$(rbenv version | sed -e "s/ (set.*$//")›%{$reset_color%}'
  fi
fi
```

I'd like to get a feedback on this approach.

**Comment by caiogondim** [comment]
A unifying Ruby segment makes more sense.
@CassioGodinho Could you make another PR with only one segment for Ruby?
Maybe using @vadviktor code?

**Comment by vadviktor** [comment]
Hey guys, I have just added a pull request to unify the RVM branch. Let me know if you'd like some more work on it.

**Comment by CassioGodinho** [comment]
Hi @vadviktor, just saw your PR.
I was away from home this last week so I didnt saw @caiogondim and your comments here. Im closing this PR since thing are sorted out on yours :)

**Comment by vadviktor** [comment]
@CassioGodinho I am truly sorry, I am getting used to communicating on Github and OSS. :sweat:

**Comment by CassioGodinho** [comment]
No problem at all @vadviktor :smile:

**Pull request closed without merging**
