### PR TITLE
Add command execution time segment

### PR DESCRIPTION
**Pull request by henry40408**

### CODE REVIEW

**Comment by caiogondim** [comment]
Thanks a lot for the PR.

I'm not able to test it.
Is adding `BULLETTRAIN_EXEC_TIME_SHOW=true` on `.zshrc` enough?

**Comment by caiogondim** [comment]
I was able to test with `sleep 6` on CLI.
Amazing work.

**Comment by caiogondim** [comment]
Will change the colours because contrast is very bad with my current colour scheme
screen shot 2016-01-05 at 22 10 45

**Comment by dbkaplun** [comment]
*nice*

**Comment by caiogondim** [comment]
Added BG and FG colour customisation on 4fc095d48d84d65c4f55ac58e6616b50b96e9b5e

**Comment by caiogondim** [comment]
Thing i got one bug.
If you do `sleep 6`, then `enter`, `enter` it shows the diff on time since the first one.

I would expect the time execution from the last command.

**Comment by caiogondim** [comment]
Screenshot from the above possible bug: 
screen shot 2016-01-05 at 23 02 31

**Comment by caiogondim** [comment]
Will open an issue

**Pull request merged**
