### PR TITLE
Removing unnecessary space in from of Git prompt

### PR DESCRIPTION
**Pull request by jtyr**
This PR removes unnecessary space in front of the Git prompt. The removed space is unnecessary because there always is one space at the beginning of every segment.

### CODE REVIEW

**Comment by dawikur** [comment]
:+1:

**Comment by dawikur** [comment]
No one else has commented on this but this is pretty straightforward change.

Thans @jtyr !

**Comment by caiogondim** [comment]
Looks good to me.
You can merge it @dawikur

**Comment by caiogondim** [comment]
Just realised you already did!
Amazing =)

**Pull request merged**
